### ISSUE TITLE
migrate unit_tests

### ISSUE THREAD

**Issue by lllwvlvwlll** [Moonlight-io/moonlight-ico-contract#2]
Migration of unit tests from other contract repositories to this one for CI support.

**Comment by ghost** [comment]
The unit tests will be pushed to the moonlight-ico-template repository. This is due to the lack of any kyc/presale methods in the latest iteration of the contract, which will prevent e2e testing

**Comment by ghost** [comment]
https://github.com/Moonlight-io/moonlight-ico-template/pull/2
